### ISSUE TITLE
Body armor and inventory and save after disconect?!

### ISSUE THREAD

**Issue by Armagryzor** [Sighmir/vrp_armorshop#1]
Hi Sighmir,

I bought the  Body armor but there is a little problem!

After disconect , i lost my body armor.

Also is it possible to store the body armor like a weapon ?

**Comment by Sighmir** [comment]
It's not possible to store armor like a weapon _yet_, this is only the first version of armorshop, I had the idea and came up with it in 15 minutes, the features here mentioned are to be implemented soon.

**Comment by Armagryzor** [comment]
Thank's for all your job!!

I love it!!

**Comment by Sighmir** [comment]
Since the Store Armor functionality acts in a button I created it in [vrp_basic_menu](https://github.com/Sighmir/vrp_basic_menu), only intact body armors can be stored to prevent players from storing and equiping body armor to regenerate armor. The saving feature will come soon in vrp_armorshop.
